"""Offline commit-range replay (RVW02-WS03): range resolve, no-post run, record.

The replay path reviews an arbitrary commit range of a checkout with NO PR
interaction — the review is generated by the shared range producer and the ONLY
output is the review-round record (`round.pr` is None). These tests pin the
range grammar, the offline resolve's user-facing errors (bad range, unknown
revision, no origin identity), the producer's range task wiring, and the
end-to-end no-post pipeline with the model launch faked.
"""

from __future__ import annotations

import json
import subprocess

import pytest

from shipit.agent import backend as agent_backend
from shipit.review import producer, replay
from shipit.review.diff import ReviewError
from shipit.spawn.launch import LaunchResult

_VALID = (
    '{"summary": {"status": "COMMENT", "overall_feedback": "ok"}, "comments": '
    '[{"file": "f.txt", "line": 1, "text": "t", "severity": "minor", '
    '"category": "correctness", "confidence": 0.5, "evidence": "e", "fix": ""}]}'
)


def _git(repo, *args):
    subprocess.run(
        ["git", "-C", str(repo), *args],
        check=True,
        capture_output=True,
        text=True,
    )


@pytest.fixture
def checkout(tmp_path):
    """A real two-commit checkout with an origin remote (for the record's repo key)."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "t@example.com")
    _git(repo, "config", "user.name", "t")
    _git(repo, "remote", "add", "origin", "https://github.com/acme/widget.git")
    (repo / "f.txt").write_text("one\n", encoding="utf-8")
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "first")
    (repo / "f.txt").write_text("one\ntwo\n", encoding="utf-8")
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "second")
    return repo


# --- the range grammar ---------------------------------------------------------


def test_parse_range_two_dot_and_three_dot():
    assert replay.parse_range("main..feature") == ("main", "feature", False)
    # Three-dot is the historical round-1 spelling: review from the merge base.
    assert replay.parse_range("main...feature") == ("main", "feature", True)


# `a....b` is the dot-run case: the extra dot leaks past the `...` partition into
# an endpoint (`.b`), which must be rejected AT PARSE with the grammar message,
# not degraded into a later "unknown revision '.b'".
@pytest.mark.parametrize(
    "spec", ["", "main", "..head", "base..", "a..b..c", "a....b", "a.....b"]
)
def test_parse_range_rejects_unusable_specs_with_the_grammar(spec):
    with pytest.raises(ReviewError, match="<base>..<head>"):
        replay.parse_range(spec)


def test_parse_range_keeps_dotted_tag_endpoints():
    # A revision may carry an INTERNAL dot (a tag like v1.2.3); only a boundary
    # dot is a malformed separator, so dotted tags must still parse.
    assert replay.parse_range("v1.2.3..v1.3.0") == ("v1.2.3", "v1.3.0", False)


# --- the offline resolve -------------------------------------------------------


def test_resolve_range_resolves_endpoints_diff_and_repo_identity(checkout):
    view = replay.resolve_range("HEAD~1..HEAD", workdir=str(checkout))
    assert view.repo.slug == "acme/widget"
    assert view.base_sha != view.head_sha
    assert "two" in view.diff
    assert view.changed_files == ["f.txt"]
    assert view.workdir == str(checkout)


def test_resolve_range_three_dot_reviews_from_the_merge_base(checkout):
    # On a linear history merge-base(HEAD~1, HEAD) IS HEAD~1, so the three-dot
    # spelling resolves to the same endpoints as the two-dot one — pinned so the
    # merge-base branch is exercised without building a forked history.
    two_dot = replay.resolve_range("HEAD~1..HEAD", workdir=str(checkout))
    three_dot = replay.resolve_range("HEAD~1...HEAD", workdir=str(checkout))
    assert three_dot.base_sha == two_dot.base_sha
    assert three_dot.head_sha == two_dot.head_sha


def test_unknown_revision_is_a_loud_offline_error(checkout):
    # Replay never fetches: an endpoint the checkout does not have tells the
    # operator to fetch it, rather than silently reaching for the network.
    with pytest.raises(ReviewError, match="unknown revision 'no-such-branch'"):
        replay.resolve_range("no-such-branch..HEAD", workdir=str(checkout))


def test_not_a_checkout_is_a_clean_error(tmp_path):
    with pytest.raises(ReviewError, match="not a git checkout"):
        replay.resolve_range("a..b", workdir=str(tmp_path))


def test_checkout_without_origin_cannot_key_a_record(tmp_path):
    repo = tmp_path / "bare"
    repo.mkdir()
    _git(repo, "init", "-q", "-b", "main")
    with pytest.raises(ReviewError, match="origin"):
        replay.resolve_range("HEAD~1..HEAD", workdir=str(repo))


def test_empty_diff_range_refuses_rather_than_billing_a_model_run(checkout):
    with pytest.raises(ReviewError, match="empty diff"):
        replay.resolve_range("HEAD..HEAD", workdir=str(checkout))


# --- the range producer + the no-post pipeline ----------------------------------


@pytest.fixture
def launcher(monkeypatch):
    monkeypatch.setattr(producer.shutil, "which", lambda binary: f"/usr/bin/{binary}")
    captured: dict = {}

    def _launch(cmd, *, cwd, env, timeout=None):
        captured["cmd"] = cmd
        captured["cwd"] = cwd
        captured["timeout"] = timeout
        return LaunchResult(returncode=0, stdout=_VALID, stderr="")

    captured["launch"] = _launch
    return captured


def test_range_producer_launches_in_the_checkout_with_the_git_diff_task(
    checkout, launcher
):
    view = replay.resolve_range("HEAD~1..HEAD", workdir=str(checkout))
    captured = producer.run_range_review(
        agent_backend.CODEX, view, launcher=launcher["launch"]
    )
    assert captured.review["summary"]["status"] == "COMMENT"
    # Launched in the CHECKOUT (no Tree), with the offline range task: the agent
    # reads the diff via git over the RESOLVED shas and is told there is no PR.
    assert launcher["cwd"] == str(checkout)
    prompt = launcher["cmd"][-1]
    assert f"git diff {view.base_sha}..{view.head_sha}" in prompt
    assert "NO pull request" in prompt
    assert "Do NOT call `gh`" in prompt


def test_run_replay_writes_the_round_record_and_touches_no_pr(
    checkout, launcher, tmp_path
):
    view = replay.resolve_range("HEAD~1..HEAD", workdir=str(checkout))
    result = replay.run_replay(
        agent_backend.CODEX,
        view,
        launcher=launcher["launch"],
        base_dir=tmp_path / "state",
    )
    record_path = result["record_path"]
    [line] = record_path.read_text(encoding="utf-8").splitlines()
    record = json.loads(line)
    # The record is the replay's product: range reviewed, findings, no PR.
    assert record["round.pr"] is None
    assert record["round.range"] == {
        "base": str(view.base_sha),
        "head": str(view.head_sha),
    }
    assert record["round.reviewer"] == "codex"
    [finding] = record["round.findings"]
    assert finding["severity"] == "minor"
    assert finding["disposition"] == "post"
    assert record["round.variant"]["content_hash"].startswith("sha256:")
    assert record["round.usage"]["duration_ms"] >= 0
    # The fake launcher's stdout carries no codex tokens line, so the round's
    # token cost is EXPLICITLY unknown (latency-only) — never a fabricated 0.
    assert record["round.usage"]["total_tokens"] is None
    # Repo-keyed under the review-rounds kind, outside the checkout.
    assert "review-rounds" in str(record_path)
    assert "acme" in str(record_path) and "widget" in str(record_path)


def test_run_replay_records_cli_reported_usage_on_the_round(
    checkout, launcher, tmp_path
):
    # RVW03-WS04 (#667): a backend whose CLI reports usage (codex's stderr
    # "tokens used" figure) lands a NON-NULL round.usage.total_tokens — measured
    # at launch-result level, no transcript/run_id join involved.
    def _launch(cmd, *, cwd, env, timeout=None):
        return LaunchResult(
            returncode=0, stdout=_VALID, stderr="codex\ntokens used\n1,234\n"
        )

    view = replay.resolve_range("HEAD~1..HEAD", workdir=str(checkout))
    result = replay.run_replay(
        agent_backend.CODEX,
        view,
        launcher=_launch,
        base_dir=tmp_path / "state",
    )
    [line] = result["record_path"].read_text(encoding="utf-8").splitlines()
    record = json.loads(line)
    assert record["round.usage"]["total_tokens"] == 1234


def test_run_replay_propagates_a_record_write_failure(
    checkout, launcher, tmp_path, monkeypatch
):
    # The replay record is the PRODUCT, not fail-open telemetry (unlike the
    # review-path tee): a write failure PROPAGATES rather than being swallowed.
    view = replay.resolve_range("HEAD~1..HEAD", workdir=str(checkout))

    def boom(*args, **kwargs):
        raise OSError("store unwritable")

    monkeypatch.setattr(replay.roundrecord, "record_round", boom)
    with pytest.raises(OSError, match="store unwritable"):
        replay.run_replay(
            agent_backend.CODEX,
            view,
            launcher=launcher["launch"],
            base_dir=tmp_path / "state",
        )


# --- the CLI verb's user-facing errors ------------------------------------------


def test_replay_verb_unknown_agent_is_one_clean_error_line(capsys):
    from shipit.verbs.pr import review as review_verb

    rc = review_verb.run_replay(
        "a..b", agent="nope", model="pro", timeout="600s", instructions=None
    )
    assert rc == 1
    err = capsys.readouterr().err
    assert err.startswith("error: unknown review agent 'nope'")


def test_replay_verb_bad_range_is_one_clean_error_line(checkout, capsys, monkeypatch):
    from shipit.verbs.pr import review as review_verb

    monkeypatch.chdir(checkout)
    rc = review_verb.run_replay(
        "nonsense", agent="codex", model="pro", timeout="600s", instructions=None
    )
    assert rc == 1
    assert "error: unusable commit range 'nonsense'" in capsys.readouterr().err


def test_replay_verb_unreadable_instructions_die_before_any_run(capsys, tmp_path):
    from shipit.verbs.pr import review as review_verb

    rc = review_verb.run_replay(
        "a..b",
        agent="codex",
        model="pro",
        timeout="600s",
        instructions=str(tmp_path / "missing.txt"),
    )
    assert rc == 1
    assert "error: cannot read review instructions" in capsys.readouterr().err


def test_replay_verb_bad_timeout_is_one_clean_error_line_before_any_run(capsys):
    # A malformed --timeout is user input on a new CLI path: it must die as one
    # `error: …` line at preflight (before resolve_range or any model run bills),
    # not as a raw ValueError traceback from the producer's _seam_deadline.
    from shipit.verbs.pr import review as review_verb

    rc = review_verb.run_replay(
        "a..b", agent="codex", model="pro", timeout="bad", instructions=None
    )
    assert rc == 1
    assert "error: invalid --timeout 'bad'" in capsys.readouterr().err
