from __future__ import annotations

import re
from pathlib import Path

import click
import pytest

from shipit.cli import root

REPO_ROOT = Path(__file__).parent.parent
RUNBOOK = REPO_ROOT / "docs" / "dev" / "adoption-runbook.lex"
MIRROR = RUNBOOK.with_suffix(".md")

MAX_PROMPT_LINES = 30


def _runbook_text() -> str:
    return RUNBOOK.read_text(encoding="utf-8")


def _prompt_block(text: str, subject: str) -> list[str]:
    pattern = re.compile(
        rf"^\s*{re.escape(subject)}:\n(.*?)^\s*:: prompt ::\s*$",
        re.DOTALL | re.MULTILINE,
    )
    match = pattern.search(text)
    assert match is not None, f"runbook lost its '{subject}:' verbatim block"
    return [line for line in match.group(1).splitlines() if line.strip()]


def test_runbook_and_mirror_exist():
    assert RUNBOOK.is_file(), "adoption runbook missing"
    assert MIRROR.is_file(), (
        "adoption runbook .md mirror missing — the ADP01 flow links the "
        "rendered projection; regenerate via tools/lex-convert-doc.sh"
    )
    assert "autogenerated from the Lex file" in MIRROR.read_text(encoding="utf-8")


@pytest.mark.parametrize("subject", ["Prompt A", "Prompt B"])
def test_survival_prompts_exist_and_stay_short(subject: str):
    lines = _prompt_block(_runbook_text(), subject)
    assert lines, f"{subject} block is empty"
    assert len(lines) <= MAX_PROMPT_LINES, (
        f"{subject} has grown to {len(lines)} non-blank lines "
        f"(cap {MAX_PROMPT_LINES}) — a survival prompt must stay short; "
        "trim it rather than raising the cap"
    )


def _shipit_invocations(text: str) -> list[str]:
    spans = re.findall(r"`([^`\n]+)`", text)
    return [s for s in spans if s == "shipit" or s.startswith("shipit ")]


def test_every_referenced_shipit_invocation_exists():
    invocations = _shipit_invocations(_runbook_text())
    assert invocations, "runbook references no shipit invocations at all"

    for invocation in invocations:
        tokens = invocation.split()[1:]
        cmd: click.Command = root
        while tokens and not tokens[0].startswith("-"):
            if not isinstance(cmd, click.Group):
                break
            token = tokens.pop(0)
            assert token in cmd.commands, (
                f"`{invocation}`: no such subcommand '{token}' — the runbook "
                "references tooling that does not exist"
            )
            cmd = cmd.commands[token]
        known_opts = {
            opt
            for param in cmd.get_params(click.Context(cmd))
            for opt in (*param.opts, *param.secondary_opts)
        }
        for token in tokens:
            if token.startswith("-"):
                assert token in known_opts, (
                    f"`{invocation}`: '{cmd.name}' has no option '{token}' — "
                    "the runbook references tooling that does not exist"
                )
