from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from shipit.install.splice import extract_block, splice_block
from shipit.install.units import BLOCK_CLOSE, BLOCK_OPEN

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "tools" / "lex-convert-doc.sh"

LEXD_BODY = "# Title\n\nFresh body from lexd.\n"
PREAMBLE = "<!-- This is autogenerated from the Lex file, do not hand edit -->"

INNER = (
    "## Development workflow (managed by shipit)\n"
    "\n"
    "Install-owned bytes; the .lex source has no counterpart for these."
)


def _stub(bindir: Path, name: str, body: str) -> None:
    exe = bindir / name
    exe.write_text(f"#!/usr/bin/env bash\n{body}\n")
    exe.chmod(0o755)


@pytest.fixture
def stub_path(tmp_path: Path) -> dict[str, str]:
    bindir = tmp_path / "stub-bin"
    bindir.mkdir()
    _stub(bindir, "lexd", f"printf '%b' {LEXD_BODY!r}")
    _stub(bindir, "prettier", 'cat "$3"')
    return {**os.environ, "PATH": f"{bindir}:{os.environ['PATH']}"}


def _run(src: Path, env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(SCRIPT), str(src)],
        env=env,
        capture_output=True,
        text=True,
    )


def _write_doc_pair(tmp_path: Path, md_text: str) -> tuple[Path, Path]:
    src = tmp_path / "doc.lex"
    src.write_text("irrelevant — the lexd stub ignores its input\n")
    dest = tmp_path / "doc.md"
    dest.write_text(md_text)
    return src, dest


def test_regenerates_clean_mirror_without_block(tmp_path, stub_path):
    src, dest = _write_doc_pair(tmp_path, "old body, no managed block\n")

    result = _run(src, stub_path)

    assert result.returncode == 0, result.stderr
    assert dest.read_text() == f"{PREAMBLE}\n\n{LEXD_BODY}"


def test_preserves_managed_block_byte_identical(tmp_path, stub_path):
    old = splice_block(f"{PREAMBLE}\n\nstale body\n", INNER)
    src, dest = _write_doc_pair(tmp_path, old)

    result = _run(src, stub_path)

    assert result.returncode == 0, result.stderr
    regenerated = dest.read_text()
    assert regenerated == splice_block(f"{PREAMBLE}\n\n{LEXD_BODY}", INNER)
    assert extract_block(regenerated) == INNER


def test_regeneration_is_idempotent_with_block(tmp_path, stub_path):
    old = splice_block(f"{PREAMBLE}\n\nstale body\n", INNER)
    src, dest = _write_doc_pair(tmp_path, old)

    assert _run(src, stub_path).returncode == 0
    first = dest.read_text()
    assert _run(src, stub_path).returncode == 0
    assert dest.read_text() == first


def test_corrupt_block_fails_loud_and_leaves_mirror_untouched(tmp_path, stub_path):
    corrupt = f"body\n\n{BLOCK_OPEN}\nblock with no closing sentinel\n"
    src, dest = _write_doc_pair(tmp_path, corrupt)

    result = _run(src, stub_path)

    assert result.returncode != 0
    assert "closing sentinel" in result.stderr
    assert dest.read_text() == corrupt


def test_script_sentinels_match_units_constants():
    script = SCRIPT.read_text()
    assert f"MANAGED_OPEN='{BLOCK_OPEN}'" in script
    assert f"MANAGED_CLOSE='{BLOCK_CLOSE}'" in script
