"""tools/lex-convert-doc.sh — the .lex → .md mirror converter (#363).

The regression under test: `shipit install` splices a sentinel-delimited
managed block into some mirrors (AGENTS.md) that has NO counterpart in the
.lex source, so a wholesale regeneration used to silently delete it. The
converter must round-trip that block byte-identical.

Hermetic: `lexd` and `prettier` are stubbed onto PATH, so the tests exercise
the script's assembly logic (preamble + body + preserved block) without the
provisioned lint env. The sentinels are imported from
``shipit.install.units`` — the source of truth — so a drift between the
script's literals and the Python constants fails here, not in a consumer repo.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from shipit.install.splice import extract_block, splice_block
from shipit.install.units import BLOCK_CLOSE, BLOCK_OPEN

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "tools" / "lex-convert-doc.sh"

LEXD_BODY = "# Title\n\nFresh body from lexd.\n"
PREAMBLE = "<!-- This is autogenerated from the Lex file, do not hand edit -->"

INNER = (
    "## Development workflow (managed by shipit)\n"
    "\n"
    "Install-owned bytes; the .lex source has no counterpart for these."
)


def _stub(bindir: Path, name: str, body: str) -> None:
    exe = bindir / name
    exe.write_text(f"#!/usr/bin/env bash\n{body}\n")
    exe.chmod(0o755)


@pytest.fixture
def stub_path(tmp_path: Path) -> dict[str, str]:
    """A PATH whose lexd emits a fixed body and whose prettier is a pass-through."""
    bindir = tmp_path / "stub-bin"
    bindir.mkdir()
    # %b so the repr's \n escapes become real newlines in the stub's output.
    _stub(bindir, "lexd", f"printf '%b' {LEXD_BODY!r}")
    # The script calls `prettier --parser markdown <file>`; cat the file arg ($3).
    _stub(bindir, "prettier", 'cat "$3"')
    return {**os.environ, "PATH": f"{bindir}:{os.environ['PATH']}"}


def _run(src: Path, env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(SCRIPT), str(src)],
        env=env,
        capture_output=True,
        text=True,
    )


def _write_doc_pair(tmp_path: Path, md_text: str) -> tuple[Path, Path]:
    src = tmp_path / "doc.lex"
    src.write_text("irrelevant — the lexd stub ignores its input\n")
    dest = tmp_path / "doc.md"
    dest.write_text(md_text)
    return src, dest


def test_regenerates_clean_mirror_without_block(tmp_path, stub_path):
    src, dest = _write_doc_pair(tmp_path, "old body, no managed block\n")

    result = _run(src, stub_path)

    assert result.returncode == 0, result.stderr
    assert dest.read_text() == f"{PREAMBLE}\n\n{LEXD_BODY}"


def test_preserves_managed_block_byte_identical(tmp_path, stub_path):
    # Build the old mirror exactly the way `shipit install` does: splice the
    # block into the previously generated markdown.
    old = splice_block(f"{PREAMBLE}\n\nstale body\n", INNER)
    src, dest = _write_doc_pair(tmp_path, old)

    result = _run(src, stub_path)

    assert result.returncode == 0, result.stderr
    regenerated = dest.read_text()
    # Body is regenerated; the block rides along at EOF, blank-line separated —
    # the same placement splice_block uses on a fresh insert.
    assert regenerated == splice_block(f"{PREAMBLE}\n\n{LEXD_BODY}", INNER)
    # The install-side reconciliation reads the inner via extract_block; the
    # round-trip must hand back the identical bytes or the [managed] hash drifts.
    assert extract_block(regenerated) == INNER


def test_regeneration_is_idempotent_with_block(tmp_path, stub_path):
    old = splice_block(f"{PREAMBLE}\n\nstale body\n", INNER)
    src, dest = _write_doc_pair(tmp_path, old)

    assert _run(src, stub_path).returncode == 0
    first = dest.read_text()
    assert _run(src, stub_path).returncode == 0
    assert dest.read_text() == first


def test_corrupt_block_fails_loud_and_leaves_mirror_untouched(tmp_path, stub_path):
    corrupt = f"body\n\n{BLOCK_OPEN}\nblock with no closing sentinel\n"
    src, dest = _write_doc_pair(tmp_path, corrupt)

    result = _run(src, stub_path)

    assert result.returncode != 0
    assert "closing sentinel" in result.stderr
    assert dest.read_text() == corrupt


def test_script_sentinels_match_units_constants():
    """The bash literals are a transcription of units.py — pin them together."""
    script = SCRIPT.read_text()
    assert f"MANAGED_OPEN='{BLOCK_OPEN}'" in script
    assert f"MANAGED_CLOSE='{BLOCK_CLOSE}'" in script
