#!/usr/bin/env bash
#
# lex-convert-doc.sh [--no-preamble] <path-to-lex-file>
#
# Converts a single Lex document to Markdown. The output is written next to the
# source: same parent directory, same base name, with the .lex extension
# replaced by .md.
#
# Unless --no-preamble is given, a "do not hand edit" comment is prepended to
# the generated Markdown.

set -euo pipefail

PREAMBLE='<!-- This is autogenerated from the Lex file, do not hand edit -->'

usage() {
    echo "Usage: $(basename "$0") [--no-preamble] <path-to-lex-file>" >&2
}

no_preamble=false
src=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-preamble)
            no_preamble=true
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        -*)
            echo "Error: unknown option '$1'" >&2
            usage
            exit 1
            ;;
        *)
            if [[ -n "$src" ]]; then
                echo "Error: only one input file may be given" >&2
                usage
                exit 1
            fi
            src="$1"
            shift
            ;;
    esac
done

if [[ -z "$src" ]]; then
    echo "Error: no input file given" >&2
    usage
    exit 1
fi

if [[ ! -f "$src" ]]; then
    echo "Error: file not found: $src" >&2
    exit 1
fi

if [[ "$src" != *.lex ]]; then
    echo "Error: expected a .lex file, got: $src" >&2
    exit 1
fi

dest="${src%.lex}.md"

# Assemble in temp files so a failure never clobbers an existing .md.
#   tmp  — raw lexd output
#   out  — preamble (optional) + body, the final document before formatting
tmp="$(mktemp)"
out="$(mktemp)"
trap 'rm -f "$tmp" "$out"' EXIT

if ! lexd "$src" --to markdown >"$tmp"; then
    echo "Error: lexd conversion failed for: $src" >&2
    exit 1
fi

if [[ "$no_preamble" == true ]]; then
    cp "$tmp" "$out"
else
    {
        printf '%s\n\n' "$PREAMBLE"
        cat "$tmp"
    } >"$out"
fi

# Format the result with the repo's pinned prettier so trivial formatting
# (trailing whitespace, stray internal spacing) can never fail the gate, and so
# a freshly generated mirror is byte-stable (idempotent). The temp has no .md
# extension, so the markdown parser is named explicitly. prettier is in the
# `lint` pixi env; if it is absent (a bare developer shell), degrade gracefully:
# warn and emit the unformatted document rather than fail the conversion.
if command -v prettier >/dev/null 2>&1; then
    fmt="$(mktemp)"
    if prettier --parser markdown "$out" >"$fmt" 2>/dev/null; then
        mv "$fmt" "$out"
    else
        rm -f "$fmt"
        echo "Error: prettier formatting failed for: $src" >&2
        exit 1
    fi
else
    echo "Warning: prettier not on PATH; emitting unformatted markdown for $src" >&2
fi

mv "$out" "$dest"

echo "Converted: $src -> $dest"
