#!/usr/bin/env bash
#
# lex-convert-doc.sh [--no-preamble] <path-to-lex-file>
#
# Converts a single Lex document to Markdown. The output is written next to the
# source: same parent directory, same base name, with the .lex extension
# replaced by .md.
#
# Unless --no-preamble is given, a "do not hand edit" comment is prepended to
# the generated Markdown.
#
# If the existing .md carries a shipit-managed block (sentinel-delimited,
# spliced in by `shipit install` — e.g. the AGENTS.md "Development workflow"
# block), it is preserved byte-identical across regeneration: extracted from
# the old mirror and re-appended at EOF, the same placement `shipit install`
# uses (#363).

set -euo pipefail

PREAMBLE='<!-- This is autogenerated from the Lex file, do not hand edit -->'

# The shipit-managed block sentinels. The block has NO counterpart in the .lex
# source, so a wholesale regeneration would silently delete it — and leave
# `.shipit.toml`'s [managed] hash describing content that is no longer there.
# These literals MUST match BLOCK_OPEN/BLOCK_CLOSE in
# src/shipit/install/units.py (the source of truth);
# tests/test_lex_convert_doc.py pins them together.
MANAGED_OPEN='<!-- Managed by shipit; do not edit. Regenerate via shipit install. -->'
MANAGED_CLOSE='<!-- End shipit-managed block. -->'

usage() {
    echo "Usage: $(basename "$0") [--no-preamble] <path-to-lex-file>" >&2
}

no_preamble=false
src=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-preamble)
            no_preamble=true
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        -*)
            echo "Error: unknown option '$1'" >&2
            usage
            exit 1
            ;;
        *)
            if [[ -n "$src" ]]; then
                echo "Error: only one input file may be given" >&2
                usage
                exit 1
            fi
            src="$1"
            shift
            ;;
    esac
done

if [[ -z "$src" ]]; then
    echo "Error: no input file given" >&2
    usage
    exit 1
fi

if [[ ! -f "$src" ]]; then
    echo "Error: file not found: $src" >&2
    exit 1
fi

if [[ "$src" != *.lex ]]; then
    echo "Error: expected a .lex file, got: $src" >&2
    exit 1
fi

dest="${src%.lex}.md"

# Assemble in temp files so a failure never clobbers an existing .md.
#   tmp  — raw lexd output
#   out  — preamble (optional) + body, the final document before formatting
tmp="$(mktemp)"
out="$(mktemp)"
trap 'rm -f "$tmp" "$out"' EXIT

if ! lexd "$src" --to markdown >"$tmp"; then
    echo "Error: lexd conversion failed for: $src" >&2
    exit 1
fi

if [[ "$no_preamble" == true ]]; then
    cp "$tmp" "$out"
else
    {
        printf '%s\n\n' "$PREAMBLE"
        cat "$tmp"
    } >"$out"
fi

# Format the result with the repo's pinned prettier so trivial formatting
# (trailing whitespace, stray internal spacing) can never fail the gate, and so
# a freshly generated mirror is byte-stable (idempotent). The temp has no .md
# extension, so the markdown parser is named explicitly. prettier is a
# provisioned tool (it lives in the `lint` pixi env); if it is absent, FAIL LOUD
# rather than emit degraded/unformatted output — run this inside the provisioned
# env (e.g. `pixi run -e lint …`).
if ! command -v prettier >/dev/null 2>&1; then
    echo "Error: prettier is not provisioned — run this inside the provisioned env (e.g. 'pixi run -e lint …')." >&2
    exit 1
fi
fmt="$(mktemp)"
if prettier --parser markdown "$out" >"$fmt" 2>/dev/null; then
    mv "$fmt" "$out"
else
    rm -f "$fmt"
    echo "Error: prettier formatting failed for: $src" >&2
    exit 1
fi

# Preserve any shipit-managed block from the existing mirror (#363). The block
# is install-owned bytes: it is re-appended AFTER prettier so formatting can
# never alter it — the round-trip must be byte-identical or the [managed] hash
# in .shipit.toml drifts. Appending at EOF matches `splice_block`'s no-anchor
# placement (body, blank line, block), so install and the mirror agree on
# where the block lives.
if [[ -f "$dest" ]] && grep -qxF "$MANAGED_OPEN" "$dest"; then
    block="$(awk -v open="$MANAGED_OPEN" -v end="$MANAGED_CLOSE" '
        $0 == open { inblock = 1 }
        inblock { print }
        inblock && $0 == end { exit }
    ' "$dest")"
    if [[ "${block##*$'\n'}" != "$MANAGED_CLOSE" ]]; then
        echo "Error: shipit-managed block in $dest has no closing sentinel — refusing to regenerate over a corrupt block. Fix the block (or rerun 'shipit install') first." >&2
        exit 1
    fi
    printf '\n%s\n' "$block" >>"$out"
fi

mv "$out" "$dest"

echo "Converted: $src -> $dest"
