#!/usr/bin/env bash
# Convert one Lex document to its adjacent Markdown projection.

set -euo pipefail

PREAMBLE='<!-- This is autogenerated from the Lex file, do not hand edit -->'

# Managed blocks have no Lex counterpart and must survive regeneration unchanged.
MANAGED_OPEN='<!-- Managed by shipit; do not edit. Regenerate via shipit install. -->'
MANAGED_CLOSE='<!-- End shipit-managed block. -->'

usage() {
    echo "Usage: $(basename "$0") [--no-preamble] <path-to-lex-file>" >&2
}

no_preamble=false
src=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-preamble)
            no_preamble=true
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        -*)
            echo "Error: unknown option '$1'" >&2
            usage
            exit 1
            ;;
        *)
            if [[ -n "$src" ]]; then
                echo "Error: only one input file may be given" >&2
                usage
                exit 1
            fi
            src="$1"
            shift
            ;;
    esac
done

if [[ -z "$src" ]]; then
    echo "Error: no input file given" >&2
    usage
    exit 1
fi

if [[ ! -f "$src" ]]; then
    echo "Error: file not found: $src" >&2
    exit 1
fi

if [[ "$src" != *.lex ]]; then
    echo "Error: expected a .lex file, got: $src" >&2
    exit 1
fi

dest="${src%.lex}.md"

# Assemble atomically so a failed conversion cannot clobber the projection.
tmp="$(mktemp)"
out="$(mktemp)"
trap 'rm -f "$tmp" "$out"' EXIT

if ! lexd "$src" --to markdown >"$tmp"; then
    echo "Error: lexd conversion failed for: $src" >&2
    exit 1
fi

if [[ "$no_preamble" == true ]]; then
    cp "$tmp" "$out"
else
    {
        printf '%s\n\n' "$PREAMBLE"
        cat "$tmp"
    } >"$out"
fi

# Name the parser because the temporary file has no Markdown extension.
if ! command -v prettier >/dev/null 2>&1; then
    echo "Error: prettier is not provisioned — run this inside the provisioned env (e.g. 'pixi run -e lint …')." >&2
    exit 1
fi
fmt="$(mktemp)"
if prettier --parser markdown "$out" >"$fmt" 2>/dev/null; then
    mv "$fmt" "$out"
else
    rm -f "$fmt"
    echo "Error: prettier formatting failed for: $src" >&2
    exit 1
fi

# Append managed bytes after formatting so their install hash stays stable.
if [[ -f "$dest" ]] && grep -qxF "$MANAGED_OPEN" "$dest"; then
    block="$(awk -v open="$MANAGED_OPEN" -v end="$MANAGED_CLOSE" '
        $0 == open { inblock = 1 }
        inblock { print }
        inblock && $0 == end { exit }
    ' "$dest")"
    if [[ "${block##*$'\n'}" != "$MANAGED_CLOSE" ]]; then
        echo "Error: shipit-managed block in $dest has no closing sentinel — refusing to regenerate over a corrupt block. Fix the block (or rerun 'shipit install') first." >&2
        exit 1
    fi
    printf '\n%s\n' "$block" >>"$out"
fi

mv "$out" "$dest"

echo "Converted: $src -> $dest"
